config/routes.rb
Mydiet::Application.routes.draw do
  root :to => 'days#index'

  resources :meal_plans

  resources :foods

  resources :meals

  resources :days

  devise_for :users

  match 'admin' => 'admin#index'
  match 'admin/welcome' => 'admin#welcome', :as => 'welcome'

end

app/models/meal_plan.rb
class MealPlan < ActiveRecord::Base
  attr_accessible :active

  # Attaching meals and allowing nested forms
  has_many :meals
  accepts_nested_attributes_for :meals, :reject_if => :all_blank, :allow_destroy => true
  
  # Returning errors related to active plan status.
  before_save :check_for_active_plan

  # Creating a way to easily get the active plan
  def self.active
    first :conditions => {:active => true}
  end

  private
  def check_for_active_plan
    if MealPlan.active.nil?
      if self.active == false
        flash[:alert] = 'You must have at least one active Meal Plan'
        return false
      end
    else
      if MealPlan.active != self && self.active == true
        oldplan = MealPlan.active
        oldplan.active = false
        oldplan.save
      end
    end
  end

end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  # GET /meal_plans
  # GET /meal_plans.json
  def index
    @meal_plans = MealPlan.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meal_plans }
    end
  end

  # GET /meal_plans/1
  # GET /meal_plans/1.json
  def show
    @meal_plan = MealPlan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal_plan }
    end
  end

  # GET /meal_plans/new
  # GET /meal_plans/new.json
  def new
    @meal_plan = MealPlan.new
    @active_plan = MealPlan.active

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal_plan }
    end
  end

  # GET /meal_plans/1/edit
  def edit
    @meal_plan = MealPlan.find(params[:id])
  end

  # POST /meal_plans
  # POST /meal_plans.json
  def create
    @meal_plan = MealPlan.new(params[:meal_plan])

    respond_to do |format|
      if @meal_plan.save
        format.html { redirect_to @meal_plan, notice: 'Meal plan was successfully created.' }
        format.json { render json: @meal_plan, status: :created, location: @meal_plan }
      else
        format.html { render action: "new" }
        format.json { render json: @meal_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meal_plans/1
  # PUT /meal_plans/1.json
  def update
    @meal_plan = MealPlan.find(params[:id])

    respond_to do |format|
      if @meal_plan.update_attributes(params[:meal_plan])
        format.html { redirect_to @meal_plan, notice: 'Meal plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_plans/1
  # DELETE /meal_plans/1.json
  def destroy
    @meal_plan = MealPlan.find(params[:id])
    @meal_plan.destroy

    respond_to do |format|
      format.html { redirect_to meal_plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
end

app/views/meal_plans/_form.html.haml
= form_for @meal_plan do |f|
  -if @meal_plan.errors.any?
    #error_explanation
      %h2= "#{pluralize(@meal_plan.errors.count, "error")} prohibited this meal_plan from being saved:"
      %ul
        - @meal_plan.errors.full_messages.each do |msg|
          %li= msg

  - unless @active_plan
    = f.hidden_field :active, :value => true

  - f.fields_for :meals do |meal|
    = render 'partials/meal_fields', :f => meal
  = link_to_add_association 'Add Meals', f, :meals

  %ul
    - if @active_plan
      %li
        = f.check_box :active
        = f.label 'Make this the active Meal Plan'

  .actions
    = f.submit 'Save', :class => 'btn'

app/views/meal_plans/edit.html.haml
%h1 Editing meal_plan

= render 'form'

= link_to 'Show', @meal_plan
\|
= link_to 'Back', meal_plans_path

app/views/meal_plans/index.html.haml
%h1 Listing meal_plans

%table
  %tr
    %th Active
    %th
    %th
    %th

  - @meal_plans.each do |meal_plan|
    %tr
      %td= meal_plan.active
      %td= link_to 'Show', meal_plan
      %td= link_to 'Edit', edit_meal_plan_path(meal_plan)
      %td= link_to 'Destroy', meal_plan, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Meal plan', new_meal_plan_path

app/views/meal_plans/new.html.haml
#new_mealplan
  %h2 New Meal Plan
  = render 'form'

app/views/meal_plans/show.html.haml
%p#notice= notice

%p
  %b Active:
  = @meal_plan.active

= link_to 'Edit', edit_meal_plan_path(@meal_plan)
\|
= link_to 'Back', meal_plans_path