config/routes.rb
Mydiet::Application.routes.draw do
  root :to => 'days#index'

  resources :meal_plans

  resources :foods

  resources :meals

  resources :days

  devise_for :users

  match 'admin' => 'admin#index'
  match 'admin/welcome' => 'admin#welcome', :as => 'welcome'

end

app/models/day.rb
class Day < ActiveRecord::Base
  attr_accessible :date, :weight, :fat
  has_many :meals

  def title
    self.date.strftime "%B #{ActiveSupport::Inflector.ordinalize(date.day)}, %Y"
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  # GET /days
  # GET /days.json
  def index
    @days = Day.all

    if @days.empty?
      redirect_to admin_path
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @days }
      end
    end
  end

  # GET /days/1
  # GET /days/1.json
  def show
    @day = Day.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @day }
    end
  end

  # GET /days/new
  # GET /days/new.json
  def new
    @day = Day.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @day }
    end
  end

  # GET /days/1/edit
  def edit
    @day = Day.find(params[:id])
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(params[:day])

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render json: @day, status: :created, location: @day }
      else
        format.html { render action: "new" }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /days/1
  # PUT /days/1.json
  def update
    @day = Day.find(params[:id])

    respond_to do |format|
      if @day.update_attributes(params[:day])
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day = Day.find(params[:id])
    @day.destroy

    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.haml
= form_for @day do |f|
  -if @day.errors.any?
    #error_explanation
      %h2= "#{pluralize(@day.errors.count, "error")} prohibited this day from being saved:"
      %ul
        - @day.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :date
    = f.date_select :date
  .actions
    = f.submit 'Save'

app/views/days/edit.html.haml
%h1 Editing day

= render 'form'

= link_to 'Show', @day
\|
= link_to 'Back', days_path

app/views/days/index.html.haml
%h1 Listing days

%table
  %tr
    %th Date
    %th
    %th
    %th

  - @days.each do |day|
    %tr
      %td= day.date
      %td= link_to 'Show', day
      %td= link_to 'Edit', edit_day_path(day)
      %td= link_to 'Destroy', day, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Day', new_day_path

app/views/days/new.html.haml
%h1 New day

= render 'form'

= link_to 'Back', days_path

app/views/days/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @day.date

= link_to 'Edit', edit_day_path(@day)
\|
= link_to 'Back', days_path