config/routes.rb
Mydiet::Application.routes.draw do
  root :to => 'days#index'

  resources :meal_plans

  resources :foods

  resources :meals

  resources :days

  devise_for :users

  match 'admin' => 'admin#index'
  match 'admin/welcome' => 'admin#welcome', :as => 'welcome'

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  attr_accessible :optional, :order, :status, :type
  belongs_to :menu, :polymorphic => true
  has_many :foods
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meals }
    end
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    @meal = Meal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/new
  # GET /meals/new.json
  def new
    @meal = Meal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/1/edit
  def edit
    @meal = Meal.find(params[:id])
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(params[:meal])

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render json: @meal, status: :created, location: @meal }
      else
        format.html { render action: "new" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meals/1
  # PUT /meals/1.json
  def update
    @meal = Meal.find(params[:id])

    respond_to do |format|
      if @meal.update_attributes(params[:meal])
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.haml
= form_for @meal do |f|
  -if @meal.errors.any?
    #error_explanation
      %h2= "#{pluralize(@meal.errors.count, "error")} prohibited this meal from being saved:"
      %ul
        - @meal.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :optional
    = f.check_box :optional
  .field
    = f.label :order
    = f.number_field :order
  .actions
    = f.submit 'Save'

app/views/meals/edit.html.haml
%h1 Editing meal

= render 'form'

= link_to 'Show', @meal
\|
= link_to 'Back', meals_path

app/views/meals/index.html.haml
%h1 Listing meals

%table
  %tr
    %th Type
    %th Status
    %th Optional
    %th Order
    %th
    %th
    %th

  - @meals.each do |meal|
    %tr
      %td= meal.type
      %td= meal.status
      %td= meal.optional
      %td= meal.order
      %td= link_to 'Show', meal
      %td= link_to 'Edit', edit_meal_path(meal)
      %td= link_to 'Destroy', meal, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Meal', new_meal_path

app/views/meals/new.html.haml
%h1 New meal

= render 'form'

= link_to 'Back', meals_path

app/views/meals/show.html.haml
%p#notice= notice

%p
  %b Type:
  = @meal.type
%p
  %b Status:
  = @meal.status
%p
  %b Optional:
  = @meal.optional
%p
  %b Order:
  = @meal.order

= link_to 'Edit', edit_meal_path(@meal)
\|
= link_to 'Back', meals_path