config/routes.rb
Mydiet::Application.routes.draw do
  root :to => 'days#index'

  resources :meal_plans

  resources :foods

  resources :meals

  resources :days

  devise_for :users

  match 'admin' => 'admin#index'
  match 'admin/welcome' => 'admin#welcome', :as => 'welcome'

end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :name, :quantity
  belongs_to :meal
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foods }
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/new
  # GET /foods/new.json
  def new
    @food = Food.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(params[:food])

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render json: @food, status: :created, location: @food }
      else
        format.html { render action: "new" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foods/1
  # PUT /foods/1.json
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.haml
= form_for @food do |f|
  -if @food.errors.any?
    #error_explanation
      %h2= "#{pluralize(@food.errors.count, "error")} prohibited this food from being saved:"
      %ul
        - @food.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :quantity
    = f.text_field :quantity
  .actions
    = f.submit 'Save'

app/views/foods/edit.html.haml
%h1 Editing food

= render 'form'

= link_to 'Show', @food
\|
= link_to 'Back', foods_path

app/views/foods/index.html.haml
%h1 Listing foods

%table
  %tr
    %th Name
    %th Quantity
    %th
    %th
    %th

  - @foods.each do |food|
    %tr
      %td= food.name
      %td= food.quantity
      %td= link_to 'Show', food
      %td= link_to 'Edit', edit_food_path(food)
      %td= link_to 'Destroy', food, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Food', new_food_path

app/views/foods/new.html.haml
%h1 New food

= render 'form'

= link_to 'Back', foods_path

app/views/foods/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @food.name
%p
  %b Quantity:
  = @food.quantity

= link_to 'Edit', edit_food_path(@food)
\|
= link_to 'Back', foods_path